version: '3.9'

services:
    database:
        container_name: database
        image: mariadb:10.9.3
        ports:
            - "0.0.0.0:3306:3306"
        environment:
            - MYSQL_DATABASE=homestead
            - MYSQL_USER=secret
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
